name: "github"
version: "0.1.1"
usage: "Install or upgrade Helm charts from GitHub repos"
description: |-
  This plugin installs or upgrades raw Helm charts from Github
command: "$HELM_PLUGIN_DIR/github.sh"
